SET ( SCORES_DB_FILE_NAME "scores.db" )

SET ( LIBB64_BUFFERSIZE "16777216" )

IF ( WIN32 )
    SET ( CORELIB_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )

IF ( WIN32 )
    SET ( ROOSNBOSS_REST_DEFINES "_UNICODE; UNICODE; WIN32_LEAN_AND_MEAN" )
ENDIF (  )


