SET ( ROOSNBOSS_PRODUCT_COMPANY_NAME "CompanyName" )
SET ( ROOSNBOSS_PRODUCT_COPYRIGHT_HOLDER "CopyrightHolder" )
SET ( ROOSNBOSS_PRODUCT_COPYRIGHT_YEAR "2014" )
SET ( ROOSNBOSS_PRODUCT_COPYRIGHT "(C) ${ROOSNBOSS_PRODUCT_COPYRIGHT_YEAR} ${ROOSNBOSS_PRODUCT_COPYRIGHT_HOLDER}" )

SET ( ROOSNBOSS_REST_PRODUCT_INTERNAL_NAME "RossNBossREST" )
SET ( ROOSNBOSS_REST_PRODUCT_NAME "Ross & Boss RESTful Web Service" )
SET ( ROOSNBOSS_REST_PRODUCT_VERSION_MAJOR "0" )
SET ( ROOSNBOSS_REST_PRODUCT_VERSION_MINOR "1" )
SET ( ROOSNBOSS_REST_PRODUCT_VERSION_PATCH "0" )
SET ( ROOSNBOSS_REST_PRODUCT_DESCRIPTION "This is the RESTful web service for Ross & Boss" )

IF ( EXISTS "${PROJECT_SOURCE_DIR}/.git" )
    EXEC_PROGRAM ( ${GIT_EXECUTABLE}
        ARGS "--git-dir=\"${PROJECT_SOURCE_DIR}/.git\" --work-tree=\"${PROJECT_SOURCE_DIR}\" describe --always"
        OUTPUT_VARIABLE GIT_SHORT_REVISION_HASH )
    SET ( ROOSNBOSS_REST_PRODUCT_VERSION_REVISION ${GIT_SHORT_REVISION_HASH} )
ELSE (  )
    SET ( ROOSNBOSS_REST_PRODUCT_VERSION_REVISION "{non-git}" )
ENDIF (  )

SET ( ROOSNBOSS_REST_PRODUCT_VERSION "${ROOSNBOSS_REST_PRODUCT_VERSION_MAJOR}.${ROOSNBOSS_REST_PRODUCT_VERSION_MINOR}.${ROOSNBOSS_REST_PRODUCT_VERSION_PATCH}-${ROOSNBOSS_REST_PRODUCT_VERSION_REVISION}" )


