#ifndef VERSIONINFO_HPP
#define VERSIONINFO_HPP


#define     VERSION_INFO_BUILD_COMPILER             PRODUCT_BUILD_COMPILER
#define     VERSION_INFO_BUILD_DATE                 __DATE__ " " __TIME__
#define     VERSION_INFO_BUILD_HOST                 PRODUCT_BUILD_HOST
#define     VERSION_INFO_BUILD_PROCESSOR            PRODUCT_BUILD_PROCESSOR
#define     VERSION_INFO_BUILD_SYSTEM               PRODUCT_BUILD_SYSTEM

#define     VERSION_INFO_PRODUCT_COMPANY_NAME       PRODUCT_COMPANY_NAME
#define     VERSION_INFO_PRODUCT_COPYRIGHT_HOLDER   PRODUCT_COPYRIGHT_HOLDER
#define     VERSION_INFO_PRODUCT_COPYRIGHT_YEAR     PRODUCT_COPYRIGHT_YEAR
#define     VERSION_INFO_PRODUCT_COPYRIGHT          PRODUCT_COPYRIGHT

#define     VERSION_INFO_PRODUCT_INTERNAL_NAME      PRODUCT_PRODUCT_INTERNAL_NAME
#define     VERSION_INFO_PRODUCT_NAME               PRODUCT_PRODUCT_NAME
#define     VERSION_INFO_PRODUCT_VERSION_MAJOR      PRODUCT_VERSION_MAJOR
#define     VERSION_INFO_PRODUCT_VERSION_MINOR      PRODUCT_VERSION_MINOR
#define     VERSION_INFO_PRODUCT_VERSION_PATCH      PRODUCT_VERSION_PATCH
#define     VERSION_INFO_PRODUCT_VERSION_REVISION   PRODUCT_VERSION_REVISION
#define     VERSION_INFO_PRODUCT_VERSION            PRODUCT_VERSION
#define     VERSION_INFO_PRODUCT_DESCRIPTION        PRODUCT_DESCRIPTION


#endif /* VERSIONINFO_HPP */


